# -*- coding: utf-8 -*-
"""assi01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1we8AD-p5j5GutE470OHj-sxAUatcg2ei
"""

# Q.1
for i in range(1,25):
  print(i)

